osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9.4
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=7
          - BREW_GCC="brew update && brew install --verbose gcc@7 && CC=/usr/local/bin/gcc-7 && CXX=/usr/local/bin/g++-7"
          - SET_GCC_ENV="cd /usr/local/bin && sudo ln -s gcc-7 cc && sudo ln -s g++-7 c++ && sudo ln -s gcc-7 gcc && sudo ln -s g++-7 g++ && cd -"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - if ! test -z $GCC_ON_MACOS; then echo "Setting GCC as default..." && eval ${SET_GCC_ENV}; fi
  - gcc -v
  - g++ -v
  - cc -v
  - c++ -v
  - xcrun -sdk macosx --show-sdk-path
  - which gcc-7
  - which g++-7
#  - echo $PATH
#  - sudo ln -f -s /usr/local/bin/gcc-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/gcc
#  - sudo ln -f -s /usr/local/bin/gcc-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/cc
#  - sudo ln -f -s /usr/local/bin/g++-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/g++
#  - sudo ln -f -s /usr/local/bin/g++-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/c++
#  - sudo ln -f -s /usr/local/bin/gcc-ar-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/ar
#  - sudo ln -f -s /usr/local/bin/gcc-nm-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/nm
#  - sudo ln -f -s /usr/local/bin/gcc-ranlib-7 /Applications/Xcode-10.1.app/Contents/Developer/usr/bin/ranlib
#  - export QMAKE_CC=/usr/local/bin/gcc-7
#  - export QMAKE_CXX=/usr/local/bin/g++-7
  
  
install:


script:
  - pip install wheel
  - pip install conan --upgrade
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install qt/5.11.3@bincrafters/stable -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++ --build missing
  - /Users/travis/.conan/data/qt/5.11.3/bincrafters/stable/source/qt5/configure -shared -confirm-license -nomake examples -nomake tests -prefix /Users/travis/.conan/data/qt/5.11.3/bincrafters/stable/package/21b96820675b48309c8fe7baef60b403e7780ccd -opensource -release -platform macx-g++ -qt-zlib
  - cat /Users/travis/build/el7addad/ConanSandbox/.qmake.stash
  - make
