osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode10.1
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=8
          - BREW_GCC="brew update && brew install --verbose gcc@7 && CC=gcc-7 && CXX=g++-7"
          - SET_GCC_ENV="cd /usr/local/bin && sudo ln -s gcc-7 cc && sudo ln -s g++-7 c++ && cd -"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - if ! test -z $GCC_ON_MACOS; then echo "Setting GCC as default..." && eval ${SET_GCC_ENV}; fi
  - gcc -v
  - g++ -v
  - cc -v
  - c++ -v
  
install:


script:
  - pip install wheel
  - pip install conan --upgrade
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
  - export QMAKE_MAC_SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
  - conan install qt/5.11.3@bincrafters/stable -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++ --build missing
  - /Users/travis/.conan/data/qt/5.11.3/bincrafters/stable/source/qt5/configure -shared -confirm-license -nomake examples -nomake tests -prefix /Users/travis/.conan/data/qt/5.11.3/bincrafters/stable/package/21b96820675b48309c8fe7baef60b403e7780ccd -opensource -release -skip qtserialport -skip qtwebchannel -skip qtwebglplugin -skip qtlocation -skip qtdeclarative -skip qtimageformats -skip qtandroidextras -skip qtconnectivity -skip qtscxml -skip qtwebengine -skip qtwebsockets -skip qtwayland -skip qtactiveqt -skip qtmultimedia -skip qtdoc -skip qtwebview -skip qttranslations -skip qt3d -skip qtscript -skip qtnetworkauth -skip qtmacextras -skip qtgraphicaleffects -skip qtx11extras -skip qtsvg -skip qtcharts -skip qtsensors -skip qtquickcontrols2 -skip qtspeech -skip qtremoteobjects -skip qtquickcontrols -skip qtserialbus -skip qtgamepad -skip qtvirtualkeyboard -skip qtwinextras -skip qtdatavis3d -skip qttools -skip qtcanvas3d -skip qtpurchasing -skip qtxmlpatterns -opengl desktop -no-openssl -no-framework -qt-zlib
  - make