osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode10.1
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=8
          - BREW_GCC="brew update && brew install --verbose gcc@7 && CC=gcc-7 && CXX=g++-7"
          - SET_GCC_ENV="cd /usr/local/bin && sudo ln -s gcc-7 cc && sudo ln -s g++-7 c++ && cd -"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - if ! test -z $GCC_ON_MACOS; then echo "Setting GCC as default..." && eval ${SET_GCC_ENV}; fi
  - gcc -v
  - g++ -v
  - cc -v
  - c++ -v
  
install:


script:
  - pip install wheel
  - pip install conan --upgrade
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - export QMAKESPEC=macx-clang
  - ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
  - export QMAKE_MAC_SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
  - conan install qt/5.11.3@bincrafters/stable -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++ --build missing
  - conan install qt/5.11.3@bincrafters/stable -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++ -o qt:qt3d=True -o qt:qtcharts=True --build missing
