osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9.4
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=7
          - BREW_GCC="brew update && brew install --verbose gcc@7 && CC=/usr/local/bin/gcc-7 && CXX=/usr/local/bin/g++-7"
          - SET_GCC_ENV="cd /usr/local/bin && sudo ln -s gcc-7 cc && sudo ln -s g++-7 c++ && sudo ln -s gcc-7 gcc && sudo ln -s g++-7 g++ && cd -"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - if ! test -z $GCC_ON_MACOS; then echo "Setting GCC as default..." && eval ${SET_GCC_ENV}; fi
  - gcc -v
  - g++ -v
  - cc -v
  - c++ -v
  - xcrun -sdk macosx --show-sdk-path
  - which gcc-7
  - which g++-7
  - brew install pkg-config
  - sudo ln -f -s /usr/local/bin/gcc-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/gcc
  - sudo ln -f -s /usr/local/bin/gcc-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/cc
  - sudo ln -f -s /usr/local/bin/g++-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/g++
  - sudo ln -f -s /usr/local/bin/g++-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/c++
  - sudo ln -f -s /usr/local/bin/gcc-ar-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/ar
  - sudo ln -f -s /usr/local/bin/gcc-nm-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/nm
  - sudo ln -f -s /usr/local/bin/gcc-ranlib-7 /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/ranlib
  - export QMAKE_CC=/usr/local/bin/gcc-7
  - export QMAKE_CXX=/usr/local/bin/g++-7
  
  
install:


script:
  - wget https://download.qt.io/archive/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz
  - tar -xzf qt-everywhere-src-5.11.3.tar.xz
  - pwd
  - ls
  - ls qt-everywhere-src-5.11.3
  - /Users/travis/build/el7addad/ConanSandbox/qt-everywhere-src-5.11.3/configure -shared -confirm-license -nomake examples -nomake tests -prefix /Users/travis/build/el7addad/ConanSandbox/qt5 -opensource -release -qt-zlib
  - cat /Users/travis/build/el7addad/ConanSandbox/.qmake.stash
  - make
